### ISSUE TITLE
Remove the 2 Factor Authorization at Sign In

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#109]
As we discussed with Manish sir, currently we doesn't required the 2 Factor Authorization, can you please remove it for now.
![Screenshot (69)](https://user-images.githubusercontent.com/52345483/60382310-e92b5a00-9a7e-11e9-9813-fd6f0bce6a6d.png)

**Comment by palashjhabak** [comment]
Removed for now. But my suggestion is to have it. Please test and close the issue

**Comment by pradiporalcare** [comment]
thank you. test done with OK. we will plan to implement once ERP in a flow..
