### ISSUE TITLE
Displaying error on New patient SMS Sent Notification Dialog.,

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#112]
Please find the attached image that will describe the issue, mentioned above.
![error in between no  for sendong](https://user-images.githubusercontent.com/52345483/60485402-7b6b7200-9cba-11e9-8b64-ed71b86fd53d.png)

**Comment by palashjhabak** [comment]
Ok checking it

**Comment by palashjhabak** [comment]
@pradiporalcare  I am unable to reproduce this, would you mind telling me in detail which all fields you filled before submitting this new patient

**Comment by pradiporalcare** [comment]
it not occurs everytime, in between it will pop anytime, when the frontoffice team working on it,

**Comment by palashjhabak** [comment]
ok thanks. will investigate more on this from the logs. thanks.
