### ISSUE TITLE
Instead of Code in "Patient", it is displaying the Name, file attached for ref.

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#115]
[Oralcare - Palash Jhabak.pdf](https://github.com/techlift-tech/erpnext-oralcare/files/3362363/Oralcare.-.Palash.Jhabak.pdf)

**Comment by palashjhabak** [comment]
Its because this Patient has code as name only. Try it for a patient which was created after the code series was changes and it will show you the code. closing the issue.
