### ISSUE TITLE
Regarding LEAD Page 

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#146]
in the lead after going in lead and click on MAKE->PATIENT, it is successfully going in the **patient** but it will still showing in the list. ref image attached
![Screenshot (83)](https://user-images.githubusercontent.com/52345483/61618796-3fa94400-ac8b-11e9-98cb-2192d4efa245.png)

**Comment by palashjhabak** [comment]
Have made the changes, after you have created the patient the status of the Lead will go from Open to Converted.
