### ISSUE TITLE
Add the phone no. for all the places, when i m taking print.

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#150]
For your ref. currently Mobile no is only showing on Patient Appointment print, but please add those on all places in all dept. as for the reference one page is added that doesn't contain the Mobile no on print.
![WhatsApp Image 2019-07-23 at 16 33 01(1)](https://user-images.githubusercontent.com/52345483/61708159-b9176400-ad69-11e9-8ea9-41a9568905d5.jpeg)

**Comment by palashjhabak** [comment]
Sales Invoice
Patient Appointment
Patient Encounter

**Comment by surajTechlift** [comment]
done..
