### ISSUE TITLE
Changes in Print Format

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#151]
1. Rupees Sign is missing from all the print invoices.
2. In "In words", comma coming after every thousand Rupees please remove it,

![Tax Invoice](https://user-images.githubusercontent.com/52345483/61708749-2a0b4b80-ad6b-11e9-96ee-3f81cb4d108b.png)

**Comment by palashjhabak** [comment]
Removed Rounded Total. @pradiporalcare  please verify
