### ISSUE TITLE
Changes in Journal Entry page

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#153]
1. REMOVE the "Reference Date" as mentioned in attached copy.
2. REMOVE the "Reference Number" as mentioned in attached copy.
3.  Letter Head in the bottom, please remove the same, which is unnecessary.

Find the attached copy
 
![Journal Entry](https://user-images.githubusercontent.com/52345483/61709233-57a4c480-ad6c-11e9-9ce5-ba55195a04b4.png)

**Comment by surajTechlift** [comment]
done
