### ISSUE TITLE
Regarding changes in "Invoice"

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#161]
1. Please shift the position of "Patient Id" <=> "Patient Name"
2. Remove the "Rounded Total" option
3. Shift the fields as per given sequence in (1), (4), (2), (3)
![invoice](https://user-images.githubusercontent.com/52345483/62206446-767c0a00-b3af-11e9-94e1-cf3bdc25904e.png)

**Comment by palashjhabak** [comment]
- In some cases total will be rounded off by the system, how will we show then?
- Taxable amount is not the total tax its the amount on which SGST and CSST or any other tax will be applied so I think the position is correct as lets say 10% CGST has to be applies on total taxable 2200 then 10 % of 2200 = 220 is calculated from taxable amount.

**Comment by palashjhabak** [comment]
Have sent you 2 screenshots in Teams please show it to Manish Ji once.
