### ISSUE TITLE
Regarding Changes in "Receipt Entry"

### ISSUE THREAD

**Issue by pradiporalcare** [techlift-tech/erpnext-oralcare#162]
1. Please Remove "ENTRY" from title "RECEIPT ENTRY"
2. Please Change the "Party Name" to "Patient Name"
3. In between"Prepared By" and Below Line "Administrator" required space to sign, as well "checked by" should be same level with "Administrator" line as per shown in the page
![receipt entry](https://user-images.githubusercontent.com/52345483/62206492-8eec2480-b3af-11e9-939e-348beba0bee0.png)

**Comment by palashjhabak** [comment]
- Changing Party name to Patient wouldnt make sense as we would have Receipt against Invoices which will be non specific to Patients.

**Comment by palashjhabak** [comment]
This was done except for Party Name as that change is still ambiguous and is in discussion. Closing this for now. @pradiporalcare  please verify the change,
