### ISSUE TITLE
create issues from Teams Chat

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext-oralcare#38]

**Comment by surajTechlift** [comment]
these are  issues from conversation
1) In receipt of cash from unsec. Loan  registered name is not showing 
2) in Journal entry ---- what is asking for Account & Party 
3) In General ledger date should always be the financial year starting date…  i.e 1.4.18  .   It is taking only the current date (change)

4) some times gst can be claimed on expenses head..... suppose on rent ....,rent is not a item but gst is charged on it
