### ISSUE TITLE
Individual Doctors data sheet

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext-oralcare#6]

**Comment by surajTechlift** [comment]
![Screenshot from 2019-05-09 13-21-41](https://user-images.githubusercontent.com/49982705/57436632-b70b3200-725d-11e9-8973-a233248a0db4.png)
doctor's data is not showing as if i am testing on local which has 5 doctors

**Comment by surajTechlift** [comment]
in doctor filter all doctor name was showing but after selecting name of doctor data was not coming up.

    tried for all doctors and for longer period
​
